# Generated by Django 5.2.9 on 2025-12-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='term',
            field=models.CharField(choices=[('Fall', 'Güz'), ('Spring', 'Bahar'), ('Summer', 'Yaz')], default='Fall', max_length=10, verbose_name='Dönem Tipi'),
        ),
        migrations.AddField(
            model_name='semester',
            name='year',
            field=models.IntegerField(default=2024, verbose_name='Yıl'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Dönem Adı'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='Öğrenci Numarası'),
        ),
    ]
