# Generated by Django 5.2.9 on 2025-12-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='weight',
            field=models.IntegerField(default=0, help_text='Genel not ortalamasına etkisi (%)'),
        ),
    ]
